Added Using Kubernetes Files
cdimascio/generator-express-no-stress pull request #5
Opened 2017-07-13 15:52 UTC by jodejar214

2017-07-14 21:40 UTC, cdimascio requested changes

2017-07-14 21:40 UTC, cdimascio commented on app/docker/.dockerignore
> +kubernetes
remove kubernetes

2017-07-14 21:40 UTC, cdimascio commented on app/templates/server/common/server.js
> +    app.use('/'+process.env.APP_ID, express.static(`${root}/public`));
this won't work for all cases, since APP_ID is not necessarily the root of the api root

2017-07-14 21:40 UTC, cdimascio commented on app/templates/public/index.html
> +    <li><h3><a href="/<%= title %>/api-explorer/">Interactive API Doc!</a></h3></li>
title isn't correct, you may have meant root. In any case, lets leave api-explorer at the root, since its not apparent that there is a better option

2017-07-17 13:13 UTC, jodejar214 commented
The requested changes have been done.

2017-08-08 00:50 UTC, merged

2020-02-13 03:40 UTC, cdimascio commented
@all-contributors add @jodejar214 for code